name: Build iOS App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: apple/actions/setup-xcode@v2
        with:
          xcode-version: '15.0'  # Cambia a Xcode 15.0

      - name: Install dependencies (if any)
        run: |
          gem install cocoapods
          pod install  # Si usas CocoaPods, de lo contrario omite esta l√≠nea

      - name: Generate Xcode project with XcodeGen
        run: |
          xcodegen generate --spec MyFileBrowser/project.yml

      - name: Build the project
        run: |
          xcodebuild -project MyFileBrowser/MyFileBrowser.xcodeproj \
            -scheme MyFileBrowser \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=15.0' \
            clean build
